---
gateway:
  router:
    routes:
      health:
        base_path: /
        to: admin_interactor
        apis:
          check:
            method: get
            parameters:
            result:
              code: { type: string, bind_to: error_code }
              message: { type: string }
              service: { type: string }
      table:
        base_path: api/table
        to: table_interactor
        apis:
          list_table:
            method: get
            parameters:
            result:
              code: { type: string }
              message: { type: string }
              table:
                array: true
                required: false
                schema: 
                  id: { type: integer }
                  status: { type: string }
          checkout:
            method: post
            parameters:
              table_id: { type: integer }
              is_member: { type: string  }
            result:
              code: { type: string }
              message: { type: string }
              # table:
              #   array: true
              #   required: false
              #   schema: 
              #     id: { type: integer }
              #     status: { type: string }
      menu:
        base_path: api/menu
        to: menu_interactor
        apis:
          get_menu:
            method: get
            parameters:
            result:
              code: { type: string }
              message: { type: string }
              menus:
                array: true
                required: false
                schema: 
                  id: { type: integer }
                  name: { type: string }
                  price: { type: string }
                  status: { type: string }
                  quantity: { type: integer }
                  type: { type: string }
          create:
            method: post
            parameters:
              price: { type: integer }
              type: { type: string }
              name: { type: string }
              quantity: { type: integer }
            result:
              code: { type: string }
              message: { type: string }
          delete:
            method: post
            parameters:
              menu_id: { type: integer }
            result:
              code: { type: string }
              message: { type: string } 
          edit:
            method: post
            parameters:
              name: { type: string }
              price: { type: string }
              type: { type: string }
              quantity: { type: integer }
              menu_id: { type: integer }
            result:
              code: { type: string }
              message: { type: string } 
      order:
        base_path: api/order
        to: order_interactor
        apis:
          create_order:
            method: post
            parameters:
              table_id: { type: integer }
              order_details: { type: string, array: true }
              remark: { type: string, required: false }
              operator: { type: string, required: false }
            result:
              code: { type: string }
              message: { type: string }
          delete:
            method: post
            parameters:
              order_id: { type: integer }
            result:
              code: { type: string }
              message: { type: string }
          list_orders_by_table:
            method: get
            parameters:
              table_id: { type: integer }
            result:
              code: { type: string }
              message: { type: string }
              data:
                schema_inline:
                  orders_id:
                    array: true
                  orders_detail:
                    array: true
interactors:
  admin_interactor:
    operations:
      check:
  table_interactor:
    operations:
      list_table:
      checkout:
  menu_interactor:
    operations:
      get_menu:
      create:
      delete:
      edit:
  order_interactor:
    operations:
      create_order:
      list_orders_by_table:
      delete:
  bill_interactor:
    operations:
      get_bill: